/***************************************************************************************************
// -- Generated by AlteraxGen 30/09/2010 20:22:56
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
   [Serializable]
   public class OfferItem : BaseEntity
   {     
      private int	_OfferId;
      private int	_ProductId;
      private int	_VatCodeId;
      private decimal	_UnitPrice;
      private int	_NoOfUnits;
      private decimal	_Discount;
      private bool	_VatExempt;

      public override int ID
      {
         get
         {
            return base.ID;
         }
         set
         {
            base.ID = value;
         }
      }

      public int OfferId
      {
         get
         {
            return _OfferId;
         }
         set
         {
            _OfferId = value;
         }
      }

      public int ProductId
      {
         get
         {
            return _ProductId;
         }
         set
         {
            _ProductId = value;
         }
      }

      public int VatCodeId
      {
         get
         {
            return _VatCodeId;
         }
         set
         {
            _VatCodeId = value;
         }
      }

      public decimal UnitPrice
      {
         get
         {
            return _UnitPrice;
         }
         set
         {
            _UnitPrice = value;
         }
      }

      public int NoOfUnits
      {
         get
         {
            return _NoOfUnits;
         }
         set
         {
            _NoOfUnits = value;
         }
      }

      public decimal Discount
      {
         get
         {
            return _Discount;
         }
         set
         {
            _Discount = value;
         }
      }

      public bool VatExempt
      {
         get
         {
            return _VatExempt;
         }
         set
         {
            _VatExempt = value;
         }
      }
   }
}
