/***************************************************************************************************
// -- Generated by AlteraxGen 30/09/2010 20:22:56
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
    [Serializable]
    public class OfferQualificationItem : BaseEntity
    {
        private int _OfferId;
        private int _ProductId;
        private int _Qty;

        public override int ID
        {
            get
            {
                return base.ID;
            }
            set
            {
                base.ID = value;
            }
        }

        public int OfferId
        {
            get
            {
                return _OfferId;
            }
            set
            {
                _OfferId = value;
            }
        }

        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }

        public int Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                _Qty = value;
            }
        }
    }
}
