/***************************************************************************************************
// -- Generated by AlteraxGen 06/05/2009 12:38:08
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
    [Serializable]
    public class OrderNotesStatus : BaseEntity
    {
        private int _OrderID;
        private int? _AccountID;
        private int? _VanID;
        private int _OutletStoreID;

        private bool _DeliveryNotePrinted;
        private bool _InvoicePrinted;
        private bool _InvoiceReprinted;
        private bool _InvoiceProformaPrinted;
        private bool _PicklistGenerated;
        private bool _InvoicePaymentComplete;
        private DateTime _DeliveryNoteDatePrinted;
        private DateTime _InvoiceProformaDatePrinted;
        private DateTime _InvoiceDatePrinted;
        private DateTime _InvoiceDateReprinted;
        private DateTime _PicklistDateGenerated;
        private Account _Account;
        private OrderHeader _OrderHeader;
        private Van _Van;

        public override int ID
        {
            get
            {
                return base.ID;
            }
            set
            {
                base.ID = value;
            }
        }

        public int? AccountID
        {
            get
            {
                return _AccountID;
            }

            set
            {
                _AccountID = value;
            }
        }

        public int? VanID
        {
            get
            {
                return _VanID;
            }
            set
            {
                _VanID = value;
            }
        }

        public int OutletStoreID
        {
            get
            {
                return _OutletStoreID;
            }
            set
            {
                _OutletStoreID = value;
            }
        }

        public int OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                _OrderID = value;
            }
        }

        public bool DeliveryNotePrinted
        {
            get
            {
                return _DeliveryNotePrinted;
            }
            set
            {
                _DeliveryNotePrinted = value;
            }
        }

        public bool InvoicePrinted
        {
            get
            {
                return _InvoicePrinted;
            }
            set
            {
                _InvoicePrinted = value;
            }
        }

        public bool InvoiceReprinted
        {
            get
            {
                return _InvoiceReprinted;
            }
            set
            {
                _InvoiceReprinted = value;
            }
        }

        public bool InvoiceProformaPrinted
        {
            get
            {
                return _InvoiceProformaPrinted;
            }
            set
            {
                _InvoiceProformaPrinted = value;
            }
        }

        public bool InvoicePaymentComplete
        {
            get
            {
                return _InvoicePaymentComplete;
            }
            set
            {
                _InvoicePaymentComplete = value;
            }
        }

        public bool PicklistGenerated
        {
            get
            {
                return _PicklistGenerated;
            }
            set
            {
                _PicklistGenerated = value;
            }
        }

        public DateTime DeliveryNoteDatePrinted
        {
            get
            {
                return _DeliveryNoteDatePrinted;
            }
            set
            {
                _DeliveryNoteDatePrinted = value;
            }
        }

        public DateTime InvoiceProformaDatePrinted
        {
            get
            {
                return _InvoiceProformaDatePrinted;
            }
            set
            {
                _InvoiceProformaDatePrinted = value;
            }
        }

        public DateTime InvoiceDatePrinted
        {
            get
            {
                return _InvoiceDatePrinted;
            }
            set
            {
                _InvoiceDatePrinted = value;
            }
        }

        public DateTime InvoiceDateReprinted
        {
            get
            {
                return _InvoiceDateReprinted;
            }
            set
            {
                _InvoiceDateReprinted = value;
            }
        }

        public DateTime PicklistDateGenerated
        {
            get
            {
                return _PicklistDateGenerated;
            }
            set
            {
                _PicklistDateGenerated = value;
            }
        }

        public Van Van
        {
            get
            {
                return _Van;
            }
            set
            {
                _Van = value;
                if (_Van != null)
                    this._Van.OrderNotesStatus = this;

            }
        }

        public OrderHeader OrderHeader
        {
            get
            {
                return _OrderHeader;
            }
            set
            {
                _OrderHeader = value;
                if (OrderHeader != null)
                {
                    _OrderHeader.OrderNoteStatus = this;
                }
            }
        }

        public Account Account
        {
            get
            {
                return
                    _Account;
            }
            set
            {
                _Account = value;
            }
        }
    }
}
