/***************************************************************************************************
// -- Generated by AlteraxGen 09/02/2010 12:41:04
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
    [Serializable]
    public class SpecialInvoiceLine : BaseEntity
    {
        private int _SpecialInvoiceID;
        private string _Description;
        private short _OrderLineStatus;
        private int _QtyPerUnit;
        private int _NoOfUnits;
        private decimal _Discount;
        private decimal _Price;
        private string _SpecialInstructions;
        private bool _VatExempt;

        public override int ID
        {
            get
            {
                return base.ID;
            }
            set
            {
                base.ID = value;
            }
        }

        public int SpecialInvoiceID
        {
            get
            {
                return _SpecialInvoiceID;
            }
            set
            {
                _SpecialInvoiceID = value;
            }
        }

        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }

        public short OrderLineStatus
        {
            get
            {
                return _OrderLineStatus;
            }
            set
            {
                _OrderLineStatus = value;
            }
        }

        public int QtyPerUnit
        {
            get
            {
                return _QtyPerUnit;
            }
            set
            {
                _QtyPerUnit = value;
            }
        }

        public int NoOfUnits
        {
            get
            {
                return _NoOfUnits;
            }
            set
            {
                _NoOfUnits = value;
            }
        }

        public decimal Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                _Discount = value;
            }
        }

        public decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                _Price = value;
            }
        }

        public string SpecialInstructions
        {
            get
            {
                return _SpecialInstructions;
            }
            set
            {
                _SpecialInstructions = value;
            }
        }

        public bool VatExempt
        {
            get
            {
                return _VatExempt;
            }

            set
            {
                _VatExempt = value;
            }
        }
    }
}
