// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dtv", Scope = "namespace", Target = "Landmark.Dtv")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dtv")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#ContentStackPanel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#ContentText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#HeaderText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#PageScrollViewer")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.AuthenticationContext.#GetUserQuery()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Landmark.Dtv.AuthenticationContext.#LoginQuery(System.String,System.String,System.Boolean,System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Logout", Scope = "member", Target = "Landmark.Dtv.AuthenticationContext.#LogoutQuery()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.DashboardControl.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Design", "CA1057:StringUriOverloadsCallSystemUriOverloads", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#.ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#ContentStackPanel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#IntroductoryText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#LabelText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#OKButton")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#OKButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Home.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#DashboardView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#Page_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateLeft")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateLeft_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateRight")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateRight_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#SearchView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#authenticationMessage")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#cancelButton")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#layoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnButton")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnPanel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnPasswordBox")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnUserNameBox")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisation", Scope = "type", Target = "Landmark.Dtv.Organisation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisation", Scope = "member", Target = "Landmark.Dtv.Organisation.#OrganisationId")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisations", Scope = "member", Target = "Landmark.Dtv.Organisation.#Organisations")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisation", Scope = "member", Target = "Landmark.Dtv.Organisation.#ParentOrganisation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisation", Scope = "type", Target = "Landmark.Dtv.OrganisationContext")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisations", Scope = "member", Target = "Landmark.Dtv.OrganisationContext.#GetOrganisationsQuery()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.OrganisationContext.#GetOrganisationsQuery()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Organisations", Scope = "member", Target = "Landmark.Dtv.OrganisationContext.#Organisations")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PasswordControl.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Landmark.Dtv.PresentationModelBase.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.PresentationModelBase.#RaisePropertyChanged(System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ria", Scope = "type", Target = "Landmark.Dtv.RiaContext")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchBingMaps")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchBingMaps_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchButton")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchOSMaps")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchOSMaps_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#UserControl_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ListView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#MapView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#PageSizeSelector")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ResultsPanel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#SearchButton")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#SearchButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#SearchText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ShowListView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ShowListView_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ShowMapView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#ShowMapView_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SelectAddressControl.#UserControl_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#About")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#ChangePassword")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#GetLatest")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Help")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#HelpQuickAccess")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Home")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#HomeQuickAccess")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Install")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LogOff")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LogOn")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#model")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#NavigationBar")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#NewQuickAccess")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#NewValuation")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#OpenQuickAccess")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#OpenValuation")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#RecoverPassword")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#UnInstall")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#UserDisplay")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#UserLogOnTime")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "model", Scope = "member", Target = "Landmark.Dtv.ShellPresentationModel.#LogOnCommand_Executing(System.Object,Landmark.NotifyExecutingCommandEventArgs)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.UserRegistrationContext.#GetUsersQuery()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#LayoutRoot")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Valuation.#Page_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#SelectAddressPanel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ShowDashboardView")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ShowSelectAddressPanel")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "Landmark.Dtv.Shell.#OnNavigate(System.Object,Landmark.Dtv.NavigateEventArgs)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Landmark.Dtv.ShellPresentationModel.#OnViewLoaded(System.Object,Landmark.Dtv.ViewLoadedArgs)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "Landmark.Dtv.ShellPresentationModel.#OnViewLoaded(System.Object,Landmark.Dtv.ViewLoadedArgs)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Landmark.Dtv.ShellPresentationModel.#OnViewLoaded(System.Object,Landmark.Dtv.ViewLoadedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "Landmark.Dtv.ShellPresentationModel.#OnViewLoaded(System.Object,Landmark.Dtv.ViewLoadedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ExpandAll")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ProcessSteps")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "Landmark.Dtv.ValuationPresentationModel.#ExpandAllCommand_Executing(System.Object,Landmark.NotifyExecutingCommandEventArgs)")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dtv", Justification = "Naming is valid in this project")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.CustomerManager.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.CustomerManager.#ContentFrame_Navigated(System.Object,System.Windows.Navigation.NavigationEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddressDisplayControl.#Address1TextBlock", Justification = "Controls defined in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddressDisplayControl.#LayoutRoot", Justification = "Controls defined in XAML")]
[module: SuppressMessage("Microsoft.Design", "CA1061:DoNotHideBaseClassMethods", Scope = "member", Target = "Landmark.Dtv.UserPropertiesPresentationModel.#.ctor(System.Windows.FrameworkElement,Landmark.Dtv.TreeNodePresentationModel)", Justification = "Acceptabel in this case as they are base classes")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserProperties.#PageForm", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserProperties.#PageHeading", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserProperties.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Design", "CA1057:StringUriOverloadsCallSystemUriOverloads", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#.ctor(System.String)", Justification = "Acceptable in this project")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#OKButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#OKButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#IntroductoryText", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#LabelText", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ErrorWindow.#ContentStackPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#SimilarPropertiesPreviewPanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ReviewTargetPropertyPreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ReviewTargetPropertyPreviewPanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Compare1Panel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#SimilarPropertiesPreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Compare3Panel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#FinishValuationPreviewPanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#PreviewPanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Valuation.#EditButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#EnterTargetPropertyPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Panel4HolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#FindAndComparePanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Compare2Panel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#PreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Valuation.#PreviewButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Panel1HolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Panel3HolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ComparePropertiesPreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#ComparePropertiesPreviewPanelHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#FindAndComparePanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#FinishValuationPreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Panel2HolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#Compare4Panel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Valuation.#EnterTargetPropertyPreviewPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Landmark.Dtv.ImagePresenterItemPresentationModel.#ImageUrl", Justification = "Agreed but COverFlow Control requires a string")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#AddressTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#BedroomsDropDown", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#DistanceDropDown", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeMonths", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeRangeMonthsTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TypeDropDown", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#AddNewAddressIcon", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeRangeSlider", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeRangeYearsTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeGroup", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TypeTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#SearchButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#BedroomsTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#AddressTitleTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgePeriodGroup", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#TransactionAgeYears", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#AddNewAddressLabel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SimilarPropertySearchControl.#DistanceTextBlock", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#SaveButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#controlBorder", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#featureTypeTextBlock", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#FeatureContainerGrid_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#FeatureListComboBox_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#ContolHoverEndStoryBoard", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#ContolHoverStoryBoard", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#CancelPopupButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#ControlGrid", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#FeatureComboBox_SelectionChanged(System.Object,System.Windows.Controls.SelectionChangedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#rectangle", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorControl.#FeatureContainerGrid", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Landmark.Dtv.PresentationModelBase.#EditCancelled", MessageId = "Canceled", Justification = "Spelling is acceptable in this project")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Landmark.Dtv.PresentationModelBase.#.ctor()", Justification = "Acceptabel in this case as they are base classes")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.CustomerTreeViewControl.#CustomerRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.CustomerTreeViewControl.#LayoutRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#UserControl_Loaded(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchOSMaps_Checked(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchText", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchBingMaps_Checked(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchOSMaps", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchBingMaps", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#SearchButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.SearchControl.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#TargetPropertySearchSP", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateLeft_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#PlaceHolderImage", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#Page_Loaded(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#ReviewPropertyButton", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#PlaceHolderImage_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#AddNewAddress", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Landing.#InitAnimations", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.Landing.#RotateRight_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "Bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#first", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#Next_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#PrevPage_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#First_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#prev", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#next", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#Image_ImageOpened(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#Image_ImageOpened(System.Object,System.Windows.RoutedEventArgs)", MessageId = "image", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#prevPage", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#Last_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#LayoutRoot", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#Prev_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#nextPage", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#NextPage_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Identifiers")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#last", Justification = "XAML Identifier")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.OrganisationManager.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.OrganisationManager.#OrganisationList", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorWrappedList.#LayoutRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.FeatureEditorWrappedList.#ItemsPresenter_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "For Future Use")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorWrappedList.#WrappedFeatureList", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#ViewSelectorToolbar", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#LayoutRoot", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#featureEditorControl", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#ViewSelectorHolderImage", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#ValuationButton", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#EditReviewControl", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.ReviewTargetPropertyPage.#Page_Loaded(System.Object,System.Windows.RoutedEventArgs)", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.TargetPropertySearchControl.#AddNewAddressButton", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.TargetPropertySearchControl.#WatermarkedSearchValue", Justification = "Name of control in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.TargetPropertySearchControl.#SearchButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.TargetPropertySearchControl.#AddNewAddressLabel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.TargetPropertySearchControl.#AddNewAddressIcon", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.AppHelper.#GetServiceClient()", Justification = "Property is not appropriate")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#authenticationMessage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnPasswordBox", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#LogOnChildWindow", Justification = "Used in tests")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#cancelButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnUserNameBox", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#logOnButton", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#layoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorManager.#LayoutRoot", Justification = "XML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorManager.#TestControlButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "XML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorManager.#TestControlButton", Justification = "XML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.BranchManager.#BranchList", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.BranchManager.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#houseNameTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#streetTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#postCodeTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#houseNumberTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#houseNameTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#cityTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#townTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#townTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#cityTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#streetTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#ShowOnMapButton", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#houseNumberTextBox", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#postCodeTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#PageScrollViewer", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#HeaderText", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#ContentText", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.About.#ContentStackPanel", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EnterTargetPropertyControl.#MapHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EnterTargetPropertyControl.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.EnterTargetPropertyControl.#TabControl_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "bound to events in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EnterTargetPropertyControl.#AddressHolderImage", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyListControl.#PropertyListHeaderTextBlock", Justification = "Name of control in XAML")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "Landmark.Dtv.TreeNodePresentationModel.#.ctor(System.Object)", MessageId = "data", Justification = "Code not finished yet")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#Help", Justification = "XML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#NewValuation", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#UserDisplay", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#ChangePassword", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#LogOff", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#Home", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#RecoverPassword", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#LogOn", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#GetLatest", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#Install", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#OpenValuation", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#LayoutRoot", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#UnInstall", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#CustomerManager", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ShellWebTestMock.#About", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Home.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Landmark.Dtv.ChangeNotifierBase", MessageId = "Notifier", Justification = "Probably not a real word but acceptable in this projec")]
[module: SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Landmark.Dtv.ChangeNotifierBase.#RaisePropertyChanged(System.String)", Justification = "Naming convention is appropriate because it says what the method does")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#controlBorder", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#ContolHoverEndStoryBoard", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#ContolHoverStoryBoard", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#rectangle", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#ControlGrid", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorControl.#FeatureContainerGrid", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.DashboardControl.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Help", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#NewValuation", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Logo", Justification = "Name of control in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#UserDisplay", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#ChangePassword", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LogOff", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Home", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#RecoverPassword", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LogOn", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#GetLatest", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Install", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#OpenValuation", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#UnInstall", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#CustomerManager", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#About", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserManager.#UserList", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserManager.#LayoutRoot", Justification = "XAML Ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#featureEditorControl", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#photoTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#propertyTransactionsDataGrid", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#addedFeatureEditorControl", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#descriptionTextBlock", Justification = "XAML so ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#addFeatureHeaderTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#LayoutRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#relatedLinksTextBlock", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#showOnMapTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#informationTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#featureHeaderTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#transactionsTextBlock", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#DataGrid_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#headerTextBlock", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.EditReviewTargetProperty.#relatedLinksDataGrid", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorManager.#LayoutRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.FeatureEditorManager.#TestControlButton_Click(System.Object,System.Windows.RoutedEventArgs)", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorManager.#TestControlButton", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.BranchGridItemPresentationModel.#data", Justification = "XML ignoring")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControlWithMap.#AddressHolderImage", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControlWithMap.#LayoutRoot", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControlWithMap.#AddressLayout", Justification = "Controls that are referenced in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PasswordControl.#LayoutRoot", Justification = "Names of controls in XAML")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertiesWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertiesWindow.#successMessage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertiesWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Landmark.Dtv.UserManagerPresentationModel.#.ctor(System.Windows.FrameworkElement,Landmark.Dtv.TreeNodePresentationModel)")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserWindow.#closeWindow")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserWindow.#sucessMessage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewOrganisationWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewOrganisationWindow.#successMessage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewOrganisationWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureWrappedList.#LayoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.OrganisationManager.#DeleteOrganisation")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.OrganisationManager.#AddOrganisation")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.OrganisationManager.#EditOrganisation")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Landmark.Dtv.LogOnWindow.#LogOnChildWindow_KeyDown(System.Object,System.Windows.Input.KeyEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AdvancedDetailsControl.#LayoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserPropertiesWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserPropertiesWindow.#closeWindow")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.UserPropertiesWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewItemWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewItemWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Window")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Tools")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#Edit")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#File")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Shell.#View")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserProfileWindow.#successMessage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserProfileWindow.#infoMessage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserProfileWindow.#pageForm")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserProfileWindow.#layoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.NewUserProfileWindow.#closeWindow")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorReason.#FeatureReasonChildWindow")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.PropertyFeatureEditorReason.#reasonForChangeLabel")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope = "member", Target = "Landmark.Dtv.OrganisationManagerPresentationModel.#AddOrganisationCommand_Executing(System.Object,Landmark.NotifyExecutingCommandEventArgs)", MessageId = "model")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Landmark.Dtv.BranchManagerPresentationModel.#.ctor(System.Windows.FrameworkElement,Landmark.Dtv.TreeNodePresentationModel)")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorListManager.#featureEditorControl")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.FeatureEditorListManager.#featureHeaderTextBlock")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#NextPageToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#LastHolderImage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#PrevHolderImage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#LastToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#PreviousPageToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#NextPageHolderImage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#FirstHolderImage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#NextHolderImage")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#FirstToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#PrevToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#PreviousPagHolderImage")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Landmark.Dtv.ReadOnlyPresentationModelBase.#.ctor(System.Windows.FrameworkElement)")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.ImageFlowControl.#NextToolTip")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#regionTextBlock")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#regionTextBox")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#addressTextBlock")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#address1NumberTextBox")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.AddNewAddressControl.#address2NameTextBox")]

[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#Help")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#NewValuation")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#UserDisplay")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#ChangePassword")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#LogOff")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#Home")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#RecoverPassword")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#LogOn")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#GetLatest")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#Install")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#OpenValuation")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#LayoutRoot")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#UnInstall")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#CustomerManager")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Landmark.Dtv.Testing.ShellWebTestMock.#About")]
