/***************************************************************************************************
// -- Generated by AlteraxGen 06/05/2009 12:38:08
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
   public interface IOrderNotesStatusDao : IDao<OrderNotesStatus, int>
   {
       OrderNotesStatus GetByOrderId(int id);
       bool OrderStatusByOrderIDExists(int orderID);
       bool OrderStatusByOrderIDAndOrderStatusExists(int orderID, int orderStatus);
       void UpdatePaymentCompleted(int orderID, bool invoicePaymentComplete);
       List<OrderHeader> InvoicesByDateAndVan(DateTime deliveryDate, int vanId);
       void UpdateVanForInvoice(int orderID, int vanID);
   }
}
