/***************************************************************************************************
// -- Generated by AlteraxGen 28/04/2010 22:21:37
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
    public interface IOrderCreditNoteDao : IDao<OrderCreditNote, int>
    {
        bool OrderCreditNoteExistsByOrderId(int orderId);

        List<OrderLine> AvailableOrderLinesForCreditNote(int orderId);
        string GenerateCreditNo();
        bool ReferenceExists(string referenceNo);

        List<CreditNoteDetails> SearchCreditNotes(string orderNo, string invoiceNo, string customerName,
                                                  DateTime dateFrom, DateTime dateTo);

        List<OrderCreditNote> GetOrderCreditNotesByOrderId(int orderId);

        InvoiceCreditNoteDetails GetInvoiceCreditDetails(int orderNo, decimal vatRate);

        decimal GetOrderCreditNoteLineAvailableTotal(int orderCreditNoteId);
    }
}
