/***************************************************************************************************
// -- Generated by AlteraxGen 28/05/2010 17:29:05
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
   public interface ISpecialInvoiceCreditNoteDao : IDao<SpecialInvoiceCreditNote, int>
   {
   }
}
