/***************************************************************************************************
// -- Generated by AlteraxGen 21/03/2010 09:12:11
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
    public interface IStandardVatRateDao : IDao<StandardVatRate, int>
    {
        StandardVatRate Get();
        bool Exists();
    }
}
