/***************************************************************************************************
// -- Generated by AlteraxGen 03/03/2010 11:19:48
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
   public class CreditNoteDao : AbstractLTSDao<CreditNote, int>, ICreditNoteDao
   {
      public CreditNoteDao()
      {
      }

      public CreditNoteDao(LTSDataContext ctx)
         : base(ctx)
      {
      }

      public override CreditNote GetById(int id)
      {
         return db.CreditNote.Single<CreditNote>(q => q.ID == id);
      }

      public List<CreditNoteDetails> SearchCreditNotes(string orderNo, string invoiceNo, string customerName, DateTime dateFrom, DateTime dateTo, short orderStatus)
      {
          return null;
      }

   }
}
