/***************************************************************************************************
// -- Generated by AlteraxGen 30/09/2010 20:22:56
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
   public class OfferDao : AbstractLTSDao<Offer, int>, IOfferDao
   {
      public OfferDao()
      {
      }

      public OfferDao(LTSDataContext ctx)
         : base(ctx)
      {
      }

      public override Offer GetById(int id)
      {
         return db.Offer.Single<Offer>(q => q.ID == id);
      }

      public bool ExistsByName(string name)
      {
          var offer = db.Offer.SingleOrDefault<Offer>(q => q.Name == name);
          return (offer == null) ? false : true;

      }
   }
}
