/***************************************************************************************************
// -- Generated by AlteraxGen 28/04/2010 22:21:37
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class OrderCreditNoteLineDao : AbstractLTSDao<OrderCreditNoteLine, int>, IOrderCreditNoteLineDao
    {
        public OrderCreditNoteLineDao()
        {
        }

        public OrderCreditNoteLineDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public bool CheckIfCreditNoteLineExists(int creditNoteid, int orderLineId)
        {
            return ((db.OrderCreditNoteLine
                        .Where(q => q.OrderCreditNoteID == creditNoteid && q.OrderLineID == orderLineId).SingleOrDefault()) ==
                    null);
        }

        public OrderCreditNoteLine GetCreditNoteLineByOrderIdAndOrderLineId(int creditNoteid, int orderLineId)
        {
            return db.OrderCreditNoteLine
                .Where(q => q.OrderCreditNoteID == creditNoteid && q.OrderLineID == orderLineId)
                .SingleOrDefault();
        }

        public override OrderCreditNoteLine GetById(int id)
        {
            return db.OrderCreditNoteLine.Single<OrderCreditNoteLine>(q => q.ID == id);
        }
    }
}
