/***************************************************************************************************
// -- Generated by AlteraxGen 28/05/2010 17:29:05
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class SpecialInvoiceCreditNoteDao : AbstractLTSDao<SpecialInvoiceCreditNote, int>, ISpecialInvoiceCreditNoteDao
    {
        public SpecialInvoiceCreditNoteDao()
        {
        }

        public SpecialInvoiceCreditNoteDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public override SpecialInvoiceCreditNote GetById(int id)
        {
            return db.SpecialInvoiceCreditNote.Single<SpecialInvoiceCreditNote>(q => q.ID == id);
        }

        #region ISpecialInvoiceCreditNoteDao Members

        public List<SpecialInvoiceCreditNoteDetails> SearchSpecialInvoiceCreditNotes(string orderNo, string invoiceNo, string customerName, DateTime dateFrom, DateTime dateTo)
        {
            var creditNotes = (from sih in db.SpecialInvoiceHeader
                               // join ons in db.OrderNotesStatus on o.ID equals ons.OrderID
                               join cr in db.SpecialInvoiceCreditNote on sih.ID equals cr.SpecialInvoiceID
                               join c in db.Customer on sih.CustomerID equals c.ID
                               select new SpecialInvoiceCreditNoteDetails
                               {
                                   CreditNoteID = cr.ID,
                                   SpecialInvoiceID = sih.ID,
                                   OrderNo = sih.AlphaID,
                                   InvoiceNo = sih.InvoiceNo,
                                   CustomerName = c.Name,
                                   DateCreated = cr.DateCreated,
                                   Reference = cr.Reference
                               });

            return FilterCreditNotes(creditNotes,
                    orderNo,
                    invoiceNo,
                    customerName,
                    dateFrom,
                    dateTo).OrderByDescending(q => q.DateCreated).ToList<SpecialInvoiceCreditNoteDetails>();
        }

        private static IQueryable<SpecialInvoiceCreditNoteDetails> FilterCreditNotes(IQueryable<SpecialInvoiceCreditNoteDetails> creditNotes,
           string orderNo,
           string invoiceNo,
           string customerName,
           DateTime dateFrom,
           DateTime dateTo)
        {
            IQueryable<SpecialInvoiceCreditNoteDetails> filteredCreditNotes = creditNotes;
            if (!String.IsNullOrEmpty(orderNo))
            {
                filteredCreditNotes = filteredCreditNotes.Where<SpecialInvoiceCreditNoteDetails>(q => q.OrderNo.Contains(orderNo));
            }

            if (!String.IsNullOrEmpty(invoiceNo))
            {
                filteredCreditNotes = filteredCreditNotes.Where<SpecialInvoiceCreditNoteDetails>(q => q.InvoiceNo.Contains(invoiceNo));
            }

            if (!String.IsNullOrEmpty(customerName))
            {
                filteredCreditNotes = filteredCreditNotes.Where<SpecialInvoiceCreditNoteDetails>(q => q.CustomerName.Contains(customerName));
            }

            if (dateFrom != DateTime.MinValue)
            {
                filteredCreditNotes = filteredCreditNotes.Where<SpecialInvoiceCreditNoteDetails>(q => q.DateCreated >= dateFrom);
            }

            if (dateTo != DateTime.MinValue)
            {
                filteredCreditNotes = filteredCreditNotes.Where<SpecialInvoiceCreditNoteDetails>(q => q.DateCreated <= dateTo);
            }

            return filteredCreditNotes;
        }

        public List<SpecialInvoiceCreditNote> GetSpecialInvoiceCreditNotesByInvoiceId(int specialInvoiceId)
        {
            throw new NotImplementedException();
        }

        public string GenerateSpecialInvoiceCreditNo()
        {
            if (db.SpecialInvoiceCreditNote.FirstOrDefault() == null)
            {
                return "SP-CRN-1";
            }
            else
            {
                int maxInvoiceNo = (int)db.SpecialInvoiceCreditNote.Select(q => Convert.ToInt32(q.Reference.Substring(7, q.Reference.Length - 7))).Max();
                return "SP-CRN-" + (maxInvoiceNo + 1).ToString();
            }
        }

        public decimal GetSpecialInvoiceOustandingBalance(int specialInvoiceNo, int creditNote, decimal vatRate)
        {
            vatRate = (vatRate / 100) + 1;

            var creditTotal = new decimal(0.0);

            var creditNotes = db.SpecialInvoiceCreditNote.Where(q => q.SpecialInvoiceID == specialInvoiceNo).DefaultIfEmpty<SpecialInvoiceCreditNote>();
            if (creditNotes.First() != null)
            {
                var crCount = db.SpecialInvoiceCreditNote.Where(q => q.SpecialInvoiceID == specialInvoiceNo).Count();
                if (crCount > 1)
                {
                    // Check to see if Credit Note already exists
                    // In the case where Credit Note exists make sure that we do not include the original credit note balance 
                    // in the outstanding balance.
                    if (creditNote != -1)
                    {

                        creditTotal = Math.Round(((from cr in db.SpecialInvoiceCreditNote
                                                   where ((cr.SpecialInvoiceID == specialInvoiceNo) && (cr.ID != creditNote))
                                                   select (cr.VatExempt ? cr.CreditAmount : cr.CreditAmount * vatRate))).
                                                     Sum(), 2);
                    }
                    else
                    {
                        creditTotal = Math.Round((from cr in db.SpecialInvoiceCreditNote
                                                  where (cr.SpecialInvoiceID == specialInvoiceNo)
                                                  select (cr.VatExempt ? cr.CreditAmount : cr.CreditAmount * vatRate)).Sum
                                                     (), 2);
                    }
                }
            }
            return creditTotal;
        }

        public bool SpecialInvoiceCreditNoteExistsByInvoiceId(int specialInvoiceId)
        {
            return (db.SpecialInvoiceCreditNote.Where<SpecialInvoiceCreditNote>(q => q.SpecialInvoiceID == specialInvoiceId).FirstOrDefault() != null) ? true : false;
        }

        public bool ReferenceExists(string referenceNo)
        {
            return (db.SpecialInvoiceCreditNote.Where<SpecialInvoiceCreditNote>(q => q.Reference == referenceNo).FirstOrDefault() != null) ? true : false;
        }

        public SpecialInvoiceCreditNote SpecialInvoiceGetByReferenceId(string reference)
        {
            return db.SpecialInvoiceCreditNote.Where<SpecialInvoiceCreditNote>(q => q.Reference == reference).SingleOrDefault<SpecialInvoiceCreditNote>();
        }

        public SpecialInvoiceCreditNoteBalance GetSpecialInvoiceCreditBalance(int specialInvoiceId, decimal vatRate)
        {
            if (vatRate != 0)
            {
                vatRate = (vatRate / 100) + 1;
            }

            // First check to see if any Order Lines exists for Order ...
            var invoiceLineCount = (from o in db.SpecialInvoiceHeader
                                    join ol in db.SpecialInvoiceLine on o.ID equals ol.SpecialInvoiceID
                                    where ol.SpecialInvoiceID == specialInvoiceId
                                    select ol.ID).Count();
            if (invoiceLineCount == 0)
            {
                return new SpecialInvoiceCreditNoteBalance
                {
                    SpecialInvoiceID = specialInvoiceId,
                    TotalInvoiceAmount = new decimal(0.0),
                    TotalAmountCredited = new decimal(0.0), // including vat
                    Balance = new decimal(0.0)
                };
            }

            var invoiceLines = from o in db.SpecialInvoiceHeader
                               join ol in db.SpecialInvoiceLine on o.ID equals ol.SpecialInvoiceID
                               where o.ID == specialInvoiceId
                               select ol;

            var invoiceTotal = 0.0m;
            foreach (SpecialInvoiceLine line in invoiceLines)
            {
                decimal price = line.Price;
                if ((price != 0) && (line.Discount != 0))
                {
                    price = line.VatExempt ? (line.Price * line.NoOfUnits) : (line.Price * line.NoOfUnits * vatRate);
                    price -= (price / 100) * line.Discount;
                }

                invoiceTotal += price;
            }

            invoiceTotal = Math.Round(invoiceTotal, 2);

            // Now deal with Credit Notes ...
            decimal creditTotal = new decimal(0.0);

            var creditNotes = db.SpecialInvoiceCreditNote.Where(q => q.SpecialInvoiceID == specialInvoiceId).DefaultIfEmpty<SpecialInvoiceCreditNote>();
            if (creditNotes.First() != null)
            {
                creditTotal = Math.Round((from cr in db.SpecialInvoiceCreditNote
                                          where cr.SpecialInvoiceID == specialInvoiceId
                                          select (cr.VatExempt ? cr.CreditAmount : cr.CreditAmount * vatRate)).Sum(), 2);
            }

            // Now deal with taking account of SpecialInvoiceCreditNoteLineItems & Header
            //var specialInvoiceCreditNotes = (from oh in db.SpecialInvoiceCreditNote
            //                      //  join ol in db.OrderCreditNoteLine on oh.ID equals ol.OrderCreditNoteID
            //                        where oh.SpecialInvoiceID == specialInvoiceId
            //                        select oh).DefaultIfEmpty<SpecialInvoiceCreditNote>();
            //if (specialInvoiceCreditNotes.First() != null)
            //{
            //    creditTotal += Math.Round((from oh in db.SpecialInvoiceCreditNote
            //                        //       join ol in db.OrderCreditNoteLine on oh.ID equals ol.OrderCreditNoteID                                           
            //                               where oh.SpecialInvoiceID == specialInvoiceId
            //                               select ((ol.VatExempt) ? ol.Price * ol.NoOfUnits : ol.Price * ol.NoOfUnits * vatRate)).Sum(), 2);
            //}

            return new SpecialInvoiceCreditNoteBalance
            {
                SpecialInvoiceID = specialInvoiceId,
                TotalInvoiceAmount = invoiceTotal,
                TotalAmountCredited = creditTotal, // including vat
                Balance = (invoiceTotal - creditTotal)
            };
        }

        #endregion

    }
}
