/***************************************************************************************************
// -- Generated by AlteraxGen 09/02/2010 12:43:38
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
    public interface ISpecialInvoiceHeaderDao : IDao<SpecialInvoiceHeader, int>
    {
        List<SpecialInvoiceHeader> GetSpecialHeaders(string orderNo,
           string invoiceNo,
           string customerName,
           DateTime dateFrom,
           DateTime dateTo,
           short orderStatus);
    }
}
