/***************************************************************************************************
// -- Generated by AlteraxGen 30/09/2010 20:22:56
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class OfferItemDao : AbstractLTSDao<OfferItem, int>, IOfferItemDao
    {
        public OfferItemDao()
        {
        }

        public OfferItemDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public override OfferItem GetById(int id)
        {
            return db.OfferItem.Single<OfferItem>(q => q.ID == id);
        }
    }
}
