/***************************************************************************************************
// -- Generated by AlteraxGen 28/04/2010 22:21:37
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class OrderCreditNoteDao : AbstractLTSDao<OrderCreditNote, int>, IOrderCreditNoteDao
    {
        public OrderCreditNoteDao()
        {
        }

        public OrderCreditNoteDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public string GenerateCreditNo()
        {
            if (db.OrderCreditNote.FirstOrDefault() == null)
            {
                return "OCRN-1";
            }
            else
            {
                int maxInvoiceNo =
                    (int)
                    db.OrderCreditNote.Select(q => Convert.ToInt32(q.Reference.Substring(5, q.Reference.Length - 5))).Max();
                return "OCRN-" + (maxInvoiceNo + 1).ToString();
            }
        }    

        public override OrderCreditNote GetById(int id)
        {
            return db.OrderCreditNote.Single<OrderCreditNote>(q => q.ID == id);
        }

        public List<OrderLine> AvailableOrderLinesForCreditNote(int orderId)
        {
            return  (from ol in db.OrderLine
                     where (ol.OrderID == orderId)
                     select ol).ToList<OrderLine>();
        }

        public bool ReferenceExists(string referenceNo)
        {
            return (db.OrderCreditNote.Where<OrderCreditNote>(q => q.Reference == referenceNo).FirstOrDefault() != null) ? true : false;
        }
    }
}
