/***************************************************************************************************
// -- Generated by AlteraxGen 06/05/2009 12:38:08
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class OrderNotesStatusDao : AbstractLTSDao<OrderNotesStatus, int>, IOrderNotesStatusDao
    {
        public OrderNotesStatusDao()
        {
        }

        public OrderNotesStatusDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public override OrderNotesStatus GetById(int id)
        {
            return db.OrderNotesStatus.Single<OrderNotesStatus>(q => q.ID == id);
        }

        public OrderNotesStatus GetByOrderId(int id)
        {
            return db.OrderNotesStatus.Single<OrderNotesStatus>(q => q.OrderID == id);
        }

        public void UpdatePaymentCompleted(int orderID, bool invoicePaymentComplete)
        {
            string sql;
            if (invoicePaymentComplete)
            {
                sql = String.Format("UPDATE OrderNotesStatus SET InvoicePaymentComplete = {0} WHERE OrderID = {1}", 1, orderID.ToString());
            }
            else
            {
                sql = String.Format("UPDATE OrderNotesStatus SET InvoicePaymentComplete = {0} WHERE OrderID = {1}", 0, orderID.ToString());
            }
            db.ExecuteCommand(sql);
        }

        public bool OrderStatusByOrderIDExists(int orderID)
        {
            return (db.OrderNotesStatus.SingleOrDefault<OrderNotesStatus>(q => q.OrderID == orderID) == null) ? false : true;
        }

        public bool OrderStatusByOrderIDAndOrderStatusExists(int orderID, int orderStatus)
        {
            return ((from oh in db.OrderHeader
                     join ons in db.OrderNotesStatus on oh.ID equals ons.OrderID
                     where ((oh.ID == orderID) && (oh.OrderStatus == orderStatus))
                     select ons).SingleOrDefault<OrderNotesStatus>() == null) ? false : true;
        }

        public List<OrderHeader> InvoicesByDateAndVan(DateTime deliveryDate, int vanId)
        {
            return (from oh in db.OrderHeader
                     join ons in db.OrderNotesStatus on oh.ID equals ons.OrderID
                     where (((oh.OrderStatus == 2) || (oh.OrderStatus == 3)) // Invoice or Invoice printed
                        && oh.DeliveryDate == deliveryDate 
                        && ons.VanID == vanId)
                    select oh).ToList<OrderHeader>();
        }

        public void UpdateVanForInvoice(int orderID, int vanID)
        {           
            string sql;

            sql = String.Format("UPDATE OrderNotesStatus SET VanId = {0} WHERE OrderID = {1}", vanID.ToString(), orderID.ToString());                       
            db.ExecuteCommand(sql);
        }
    }
}
