/***************************************************************************************************
// -- Generated by AlteraxGen 28/04/2010 22:21:37
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class OrderCreditNoteDao : AbstractLTSDao<OrderCreditNote, int>, IOrderCreditNoteDao
    {
        public OrderCreditNoteDao()
        {
        }

        public OrderCreditNoteDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public override OrderCreditNote GetById(int id)
        {
            return db.OrderCreditNote.Single<OrderCreditNote>(q => q.ID == id);
        }

        public List<OrderLine> AvailableOrderLinesForCreditNote(int orderId)
        {
            return  (from ol in db.OrderLine
                     where (ol.OrderID == orderId)
                     select ol).ToList<OrderLine>();
        }
    }
}
