/***************************************************************************************************
// -- Generated by AlteraxGen 09/02/2010 12:43:38
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;
using SP.Core.DataInterfaces;

namespace SP.Data.LTS
{
    public class SpecialInvoiceLineDao : AbstractLTSDao<SpecialInvoiceLine, int>, ISpecialInvoiceLineDao
    {
        public SpecialInvoiceLineDao()
        {
        }

        public SpecialInvoiceLineDao(LTSDataContext ctx)
            : base(ctx)
        {
        }

        public override SpecialInvoiceLine GetById(int id)
        {
            return db.SpecialInvoiceLine.Single<SpecialInvoiceLine>(q => q.ID == id);
        }

        public List<SpecialInvoiceLine> GetBySpecialInvoiceId(int id)
        {
            return db.SpecialInvoiceLine.Where<SpecialInvoiceLine>(q => q.SpecialInvoiceID == id)
                .ToList<SpecialInvoiceLine>();

        }
    }
}
