/***************************************************************************************************
// -- Generated by AlteraxGen 03/03/2010 11:19:48
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
   public interface ICreditNoteDao : IDao<CreditNote, int>
   {
       List<CreditNoteDetails> SearchCreditNotes(          
           string orderNo, string invoiceNo, 
           string customerName, 
           DateTime dateFrom, 
           DateTime dateTo);

       InvoiceCreditNoteDetails GetInvoiceCreditDetails(int orderID);       
   }
}
