/***************************************************************************************************
// -- Generated by AlteraxGen 30/09/2010 20:22:56
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using SP.Core.Domain;

namespace SP.Core.DataInterfaces
{
    public interface IOfferQualificationItemDao : IDao<OfferQualificationItem, int>
    {
        List<OfferQualificationItem> GetByOfferId(int id);
        bool Exists(int offerId, int productId);
    }
}
