/***************************************************************************************************
// -- Generated by AlteraxGen 24/03/2009 16:45:40
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SP.Core.Domain;

namespace SP.Core.Domain
{
    [Serializable]
    public class AuditEventsArchive : BaseEntity
    {
        private string _PageName;
        private short _EventType;
        private string _Description;
        private string _Creator;
        private string _OperatingOn;
        private DateTime _CreatedDate;
        private System.Data.Linq.Binary _Version;

        public override int ID
        {
            get
            {
                return base.ID;
            }
            set
            {
                base.ID = value;
            }
        }

        public string PageName
        {
            get
            {
                return _PageName;
            }
            set
            {
                _PageName = value;
            }
        }

        public short EventType
        {
            get
            {
                return _EventType;
            }
            set
            {
                _EventType = value;
            }
        }

        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }

        public string OperatingOn
        {
            get { return _OperatingOn; }
            set { _OperatingOn = value; }
        }

        public string Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                _Creator = value;
            }
        }

        public DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                _CreatedDate = value;
            }
        }

        public System.Data.Linq.Binary Version
        {
            get
            {
                return _Version;
            }
            set
            {
                _Version = value;
            }
        }
    }
}
