/***************************************************************************************************
// -- Generated by AlteraxGen 28/04/2010 22:21:37
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
   [Serializable]
   public class OrderCreditNoteLine : BaseEntity
   {
      private int	_ID;
      private int	_OrderCreditNoteID;
      private int	_OrderLineID;
      private int	_ProductID;
      private int	_QtyPerUnit;
      private int	_NoOfUnits;
      private float	_Discount;
      private decimal	_Price;

      public override int ID
      {
         get
         {
            return base.ID;
         }
         set
         {
            base.ID = value;
         }
      }

      public int OrderCreditNoteID
      {
         get
         {
            return _OrderCreditNoteID;
         }
         set
         {
            _OrderCreditNoteID = value;
         }
      }

      public int OrderLineID
      {
         get
         {
            return _OrderLineID;
         }
         set
         {
            _OrderLineID = value;
         }
      }

      public int ProductID
      {
         get
         {
            return _ProductID;
         }
         set
         {
            _ProductID = value;
         }
      }

      public int QtyPerUnit
      {
         get
         {
            return _QtyPerUnit;
         }
         set
         {
            _QtyPerUnit = value;
         }
      }

      public int NoOfUnits
      {
         get
         {
            return _NoOfUnits;
         }
         set
         {
            _NoOfUnits = value;
         }
      }

      public float Discount
      {
         get
         {
            return _Discount;
         }
         set
         {
            _Discount = value;
         }
      }

      public decimal Price
      {
         get
         {
            return _Price;
         }
         set
         {
            _Price = value;
         }
      }
   }
}
