/***************************************************************************************************
// -- Generated by AlteraxGen 09/02/2010 12:43:38
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
    [Serializable]
    public class SpecialInvoiceHeader : BaseEntity
    {
        private int _CustomerID;
        private int _AccountID;
        private int _OutletStoreID;
        private int _VatCodeID;       
        private short _AlphaPrefixOrPostFix;
        private string _AlphaID;
        private DateTime _OrderDate;
        private DateTime _DeliveryDate;
        private short _OrderStatus;
        private string _SpecialInstructions;
        private string _InvoiceNo;
        private DateTime _DatePrinted;
        private DateTime _DateReprinted;
        private DateTime _DateCreated;
        private DateTime _DateModified;

        public override int ID
        {
            get
            {
                return base.ID;
            }
            set
            {
                base.ID = value;
            }
        }

        public int AccountID
        {
            get
            {
                return _AccountID;
            }

            set
            {
                _AccountID = value;
            }
        }

        public int OutletStoreID
        {
            get
            {
                return _OutletStoreID;
            }

            set
            {
                _OutletStoreID = value;
            }
        }

        public int CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                _CustomerID = value;
            }
        }

        public int VatCodeID
        {
            get 
            { 
                return _VatCodeID; 
            }
            
            set 
            { 
                _VatCodeID = value; 
            }
        }

        public short AlphaPrefixOrPostFix
        {
            get
            {
                return _AlphaPrefixOrPostFix;
            }
            set
            {
                _AlphaPrefixOrPostFix = value;
            }
        }

        public string AlphaID
        {
            get
            {
                return _AlphaID;
            }
            set
            {
                _AlphaID = value;
            }
        }

        public DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                _OrderDate = value;
            }
        }

        public DateTime DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                _DeliveryDate = value;
            }
        }

        public DateTime DatePrinted
        {
            get
            {
                return _DatePrinted;
            }

            set
            {
                _DatePrinted = value;
            }
        }

        public DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }

            set
            {
                _DateCreated = value;
            }
        }

        public DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                _DateModified = value;
            }
        }

        public short OrderStatus
        {
            get
            {
                return _OrderStatus;
            }
            set
            {
                _OrderStatus = value;
            }
        }

        public string SpecialInstructions
        {
            get
            {
                return _SpecialInstructions;
            }
            set
            {
                _SpecialInstructions = value;
            }
        }

        public string InvoiceNo
        {
            get
            {
                return _InvoiceNo;
            }
            set
            {
                _InvoiceNo = value;
            }
        }
    }
}
