/***************************************************************************************************
// -- Generated by AlteraxGen 03/03/2010 11:19:47
// Version 1.0
***************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SP.Core.Domain
{
    [Serializable]
    public class SpecialInvoiceCreditNoteDetails
    {
        public int SpecialInvoiceID { get; set; }
        public decimal TotalInvoiceAmount { get; set; }
        public decimal TotalAmountCredited { get; set; }
        public decimal Balance { get; set; }
    }
}
